"""Build the placeholder tiles and example map with Python's standard library."""
from pathlib import Path
import json
import struct
import zlib
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SIZE = 24
TILE = 32
PALETTE = [
    ("grass_1", "#82ad68"), ("grass_2", "#87b36c"),
    ("grass_3", "#7da762"), ("grass_4", "#8ab56f"),
    ("soil_1", "#a87950"), ("soil_2", "#b18359"),
    ("soil_3", "#b98b60"), ("path", "#dfc592"),
    ("shore", "#bfd3a0"), ("water_shallow", "#79bdcb"),
    ("water_medium", "#559dbb"), ("water_deep", "#397eaa"),
    ("boundary", "#577e50"),
]


def png(path, width, height, pixels):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    raw = b"".join(b"\0" + pixels[y * width * 3:(y + 1) * width * 3] for y in range(height))
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))


def main():
    colors = [bytes.fromhex(color[1:]) for _, color in PALETTE]
    strip = b"".join(color * TILE for color in colors)
    png(ROOT / "assets/textures/garden.png", TILE * len(colors), TILE, strip * TILE)
    ground, blocked, plantable = [], [], []
    for y in range(SIZE):
        for x in range(SIZE):
            gid = 1 + ((x * 17 + y * 31 + x * y) % 13) % 4
            boundary = x in (0, 23) or y in (0, 23)
            pond = ((x - 17.5) / 4.5) ** 2 + ((y - 6) / 3.8) ** 2
            water = pond < 0.85
            plot = (3 <= x <= 7 and 4 <= y <= 7 or
                    3 <= x <= 6 and 15 <= y <= 19 or
                    15 <= x <= 19 and 15 <= y <= 18)
            if pond < 1.25:
                gid = 9
            if water:
                gid = 10 if pond > 0.52 else 11 if pond > 0.20 else 12
            if x in (10, 11) or y in (11, 12) or (y == 17 and 7 <= x <= 9):
                gid = 8
            if plot:
                gid = 5 + (x + y) % 3
            if boundary:
                gid = 13
            ground.append(gid)
            blocked.append(13 if boundary or water else 0)
            plantable.append(5 if plot else 0)

    tileset = ET.Element("tileset", version="1.10", name="garden", tilewidth="32", tileheight="32",
                         tilecount=str(len(colors)), columns=str(len(colors)))
    ET.SubElement(tileset, "image", source="../textures/garden.png", width=str(TILE * len(colors)), height="32")
    for i, (name, _) in enumerate(PALETTE):
        tile = ET.SubElement(tileset, "tile", id=str(i))
        props = ET.SubElement(tile, "properties")
        ET.SubElement(props, "property", name="terrainId", value=name)
    ET.indent(tileset)
    ET.ElementTree(tileset).write(ROOT / "assets/tilesets/garden.tsx", encoding="UTF-8", xml_declaration=True)
    world = ET.Element("map", version="1.10", orientation="orthogonal", renderorder="right-down",
                       width="24", height="24", tilewidth="32", tileheight="32", infinite="0",
                       nextlayerid="8", nextobjectid="2")
    props = ET.SubElement(world, "properties")
    ET.SubElement(props, "property", name="mapId", value="garden_01")
    ET.SubElement(props, "property", name="mapVersion", type="int", value="1")
    ET.SubElement(world, "tileset", firstgid="1", source="../tilesets/garden.tsx")
    layers = dict(ground=ground, decoration_back=[0]*576, blocked=blocked,
                  plantable=plantable, decoration_front=[0]*576)
    for i, (name, cells) in enumerate(layers.items(), 1):
        layer = ET.SubElement(world, "layer", id=str(i), name=name, width="24", height="24",
                              visible="0" if name in ("blocked", "plantable") else "1")
        ET.SubElement(layer, "data", encoding="csv").text = "\n" + ",\n".join(
            ",".join(map(str, cells[y*24:(y+1)*24])) for y in range(24)) + "\n"
    anchors = ET.SubElement(world, "objectgroup", id="6", name="anchors")
    spawn = ET.SubElement(anchors, "object", id="1", name="spawn_main", x="336", y="400")
    ET.SubElement(spawn, "point")
    props = ET.SubElement(spawn, "properties")
    ET.SubElement(props, "property", name="anchorId", value="spawn_main")
    ET.SubElement(world, "objectgroup", id="7", name="props")
    ET.indent(world)
    ET.ElementTree(world).write(ROOT / "assets/maps/garden_01.tmx", encoding="UTF-8", xml_declaration=True)
    (ROOT / "preview/map.js").write_text("// Generated by scripts/build_background.py\nconst garden = " +
        json.dumps(dict(size=SIZE, tile=TILE, palette=PALETTE, **layers)) + ";\n")
    # A portable, full-size preview for viewing without a browser.
    pixels = b"".join(b"".join(colors[ground[(y//32)*24+x//32]-1] for x in range(768)) for y in range(768))
    png(ROOT / "preview/background.png", 768, 768, pixels)


if __name__ == "__main__":
    main()
